### ISSUE TITLE
Setting up notifications does not save

### ISSUE THREAD

**Issue by ryanp-javs** [spyder007/teamcity-msteams-notifier#13]
Hello, 
I have 2 TC instances (one legacy, one new), one is on 2019.1 and the other is on a much older version (2017.2). I have just installed the Teams notifier(2.0.0), restarted TC and configured the webhook URL. The test button does create a message in the channel so we're good there.

However, when I go to either a project or build config to add it to the MsTeams notifications, I click the link and to do so, it displays the table indicating that it has added the the project but clicking "edid" and "delete" do nothing, reloading or re-navigating to the page shows that the project or build config does not have any notifications.

Perhaps I'm doing something wrong or I am missing something but this pretty much makes the plugin unusable to us since it won't actually post anything to the channel. are there logs or anything I can check?

**Comment by ryanp-javs** [comment]
Ok, I see now, you have to first click on the link to add a notification to the project, it will then display a table with a fake entry, where you then click add once more and that one will work. it seems as though there's a bug with the initial creation. Also, it is unclear as to whether you need to re-enter the webhook url for every rule, or if you leave it blank it'll fall to the overall server config. there's also some verbiage related to channel names that are left over from the slack plugin. 

for now, the notifications are working but it'd be nice to have things a touch more polished. if I have time I may look into helping with the code.

**Comment by spyder007** [comment]
I haven't been doing much active development on this project, only as bugs come up.  

If you could comment with a task list of things you noticed that you'd like to see changed, I can either fix them immediately or create new issues, depending on the complexity

**Comment by spyder007** [comment]
I did more research:  the row you saw was actually a template row in the HTML that should have been hidden, but due to a naming issue with the styles it was not.  That should alleviate some of the confusion.

Regarding the notion of "Channels", MS Teams also has a notion of channels under teams.  I left that setting in even though, at present, the Incoming WebHooks integration with MS Teams does NOT support mentions for users or channels (see Issue #10 for details).  

I will release 2.0.1 to hide the template from that view, but as of right now, I'd like to leave the mentions sections in the configuration, even though they are currently ignored.
